### ISSUE TITLE
Add support for reopening

### ISSUE THREAD

**Issue by Gozala** [random-access-storage/random-access-storage#7]
Ink & Switch are running into problems because they create many cores which keep file open (see https://github.com/automerge/hypermerge/issues/69). As far as I understand current implementation will error all the operations after core all is closed. While it is possible to wrap around the store to add support for auto-reopening it requires duplicating significant amount of logic and queuing to avoid races.

I would like to propose to introduce `reopen` option, which if `true` isn't going to fail subsequent operations but would instead reopen core and resume the queue.

**Comment by mafintosh** [comment]
I don't think it would be much simpler to add it to the base abstraction but can be convinced.
I don't fully see how this would help you though keeping more files open?

**Comment by Gozala** [comment]
@mafintosh could you please let me know what do you think about this proposal ? I can take on and submit a patch if this looks right. If you think it is not a good idea I'll go ahead and create something along the lines of [`RandomAccessManager`](https://github.com/automerge/hypermerge/pull/72/files#diff-69c8f5a1d6af91795c312a67b8058d71) that wraps the store to add autoreopen functionality.

I don't like that route because I need to recreate logic of task queue from here with slight changes.

**Comment by mafintosh** [comment]
Landed in master as suspend
