### ISSUE TITLE
What is the expected behavior of close & destroy ?

### ISSUE THREAD

**Issue by Gozala** [random-access-storage/random-access-storage#9]
@mafintosh I would appreciate some clarification on the expected behavior. For a while I was under impression that following code would perform read / write operations in parallel and only after will close the corresponding file:

```js
ra.read(0, 12, console.log)
...
ra.read(12, 34, console.log)
ra.close(console.log)
```

But reading the code base I am under impression that `close` / `destroy` is not going to wait for scheduled read / write operations to complete before executing. It also appears that using raw node fs API all the reads will also succeed before file descriptor is closed.

```js
let fd = fs.openSync('./README.md')
let i = 0; while (i < 5000) {
  fs.read(fd, new Buffer(27), 0, 27, i += 27, console.log)
}
fs.close(fd, console.log)
```

This makes me wonder if intended behavior is to let non-blocking operations (read/write/stat/del) finish before executing blocking operations (close/delete), which happens to be the case with `random-access-file` due to how node FS API works and not because the scheduler handles it.

If above assumption is correct, then I think that current implementation is incorrect and can lead to race conditions with other random-access-storage providers.

Thanks

**Comment by mafintosh** [comment]
@Gozala close in ras will wait for all pending reada/writes to finish. Node core does not. You example from core might work but that’s undefined behaivour and can be dangerous 

Where do you see in the code of ras that close isn’t waiting?

**Comment by mafintosh** [comment]
Same goes for destroy btw, although it’s safe to unlink an open file (on unix at least) but we are nice and close it first 😛

**Comment by Gozala** [comment]
So looking at the following lines 

https://github.com/random-access-storage/random-access-storage/blob/55650e6e6f6b06e0a45382fbc11086c15ef67879/index.js#L230-L237

If queue contains several reads & then close, I am under impression that close will run and there’s nothing that will make it wait for reads to complete

**Comment by mafintosh** [comment]
Let me check

**Comment by mafintosh** [comment]
Yes, I think we have a race condition we aren't hitting in practice here (in hypercore) due to the fact that we open storage explicitly first. Let me make a another test and fix.

**Comment by mafintosh** [comment]
Indeed a bug, nice find @Gozala - fix upcoming

**Comment by mafintosh** [comment]
Fixed in https://github.com/random-access-storage/random-access-storage/commit/f00e426d61eaed40204d1fcde25378403ce0b3e6 (there is a failing test in the commit before)

Out in 1.4.1
